### ISSUE TITLE
Make connection.transaction() return an already-started transaction

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-python#117]
`connection.transaction()` should be analogous to `open()` in that it should return an already-started transaction, instead of requiring an explicit call to `start()`.

Two reasons:

1. Pre-started transaction is a very weird thing.
2. We obtain nice symmetry for context manager vs no context manager cases:

```python
tx = connection.transaction()
# ...
tx.commit()

# and

with connection.transaction() as tx:
    ...

```

**Comment by 1st1** [comment]
And for async version it will be:

```
tx = await con.transaction()

# or

async with con.transaction():
```
?

**Comment by fmoor** [comment]
`transaction.start()` has been removed.
