### ISSUE TITLE
Update Basic Usage docs section

### ISSUE THREAD

**Issue by tech-cobber** [edgedb/edgedb-python#122]
I've been following [Basic Usage](https://www.edgedb.com/docs/clients/00_python/usage#basic-usage) section of the EdgeDB documentation and this error occurred `edgedb.errors.InvalidReferenceError: type 'default::local_date' does not exist`.

I can see `local_date` was [moved](https://github.com/edgedb/edgedb/blob/master/docs/changelog/1_0_a2.rst#new-cal-module) to the `cal` module, so could you please update the [documentation](https://github.com/edgedb/edgedb-python/blob/master/docs/usage.rst#basic-usage) with `cal::local_date` like you did in [edgedb-python README](https://github.com/edgedb/edgedb-python/blob/master/README.rst#basic-usage)

If you don't mind I can do this on my own with PR.

---
By the way I can see the same thing in [edgedb README](https://github.com/edgedb/edgedb/blob/master/README.md#modern-type-safe-schema)

**Comment by 1st1** [comment]
Thanks for reporting this! We'd definitely appreciate a PR.

**Comment by tech-cobber** [comment]
Ready to PR, but can I fix this too or is it intended?

![image](https://user-images.githubusercontent.com/50849313/95004414-5d926880-05f3-11eb-977b-a11587711468.png)
