### ISSUE TITLE
Object's __hash__ and __eq__ are out of sync

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-python#127]
`Object.__hash__` takes into account all fetched pointers, essentially the hashing is similar to tuples.

`Object.__eq__` and other compare operators compare by object's EdgeDB ID.

**Comment by fmoor** [comment]
If I remember correctly the plan is to no longer use implicit `id`s in this driver so `Object.__eq__` should probably change to mimic tuples. Does this sound right?
