### ISSUE TITLE
edgedb orm

### ISSUE THREAD

**Issue by Krausso** [edgedb/edgedb-python#149]
Hey, guys! Not really much people(and most of newbies) are usually writing raw db requests using execute.
So I'm sure that will be a good feature if you'll create your personal ORM specially for edgedb instead of SQLAlchemy, Tortoise ORM or something like that.

Have you got it in ur plans?

**Comment by 1st1** [comment]
We have one in progress for TypeScript; a version for Python will shortly follow. No ETA yet, but it'll become our priority after we release 1.0.

**Comment by Krausso** [comment]
Thx for an answer, so that one more question. Will u make specified ORM for Go/C#?

**Comment by 1st1** [comment]
github.com/edegdb/edgedb-go driver is almost complete, but we haven't yet considered making an ORM-like library out of it. C# is something we'd love to get supported, but that's not in our immediate roadmap :/

**Comment by Krausso** [comment]
Okay, good luck:D
