### ISSUE TITLE
Passing in set datatype to query

### ISSUE THREAD

**Issue by rbraddev** [edgedb/edgedb-python#190]
When trying to run the below query:
```r = con.query('with module inventory select Device {ip, hostname, site} filter .site in <set>$site', site={'site1', 'site3'})```

I get the following error:
```edgedb.errors.EdgeQLSyntaxError: Unexpected 'set'```

I have also tried `<Set>`, `<set<str>>` but I get the same error.

Could anyone please help on the correct way to do this?

Thank you.

**Comment by jaclarke** [comment]
EdgeDB currently only supports query parameters that are either scalars or arrays of scalars (https://www.edgedb.com/docs/edgeql/expressions/parameters#parameter-types). So the way to do that query would be passing in an array of strings, then [unpacking that array into a set](https://www.edgedb.com/docs/edgeql/funcops/array#function::std::array_unpack):
```edgeql
with module inventory
select Device {
  ip, hostname, site
} filter .site in array_unpack(<array<str>>$site)
```

**Comment by rbraddev** [comment]
@jaclarke thank you very much!
