### ISSUE TITLE
[Question] INSERT statement returns empty Object

### ISSUE THREAD

**Issue by pedronc** [edgedb/edgedb-python#21]
Edgedb CLI returns a Set of Object with its id, while the Python Client returns a Set of empty Object after an INSERT statement. Is this the expected behavior?

**Comment by elprans** [comment]
The CLI actually uses the Python client, so the difference is in how the result is rendered.  The CLI has a custom renderer that renders ids by default, whereas the `Object.__repr__` seems not to do that. @1st1 should we render ids in object reprs by default?

**Comment by 1st1** [comment]
Yeah, I think we should.
