### ISSUE TITLE
Lots of `DeprecationWarning` on `AsyncIOPool` methods

### ISSUE THREAD

**Issue by unmade** [edgedb/edgedb-python#224]
- edgedb: `1-beta3`
- edgedb-python: `0.17.2`

Whenever I call methods on AsyncIOPool I get a lot a of warnings like in the pytest output:

```
/Users/unmade/src/unmade/shelf-back/.venv/lib/python3.9/site-packages/edgedb/asyncio_pool.py:619: DeprecationWarning: The "acquire()" method is deprecated and is scheduled to be removed. Use the query methods on Pool instead.
    async with self.acquire() as con:
```

```
/Users/unmade/src/unmade/shelf-back/.venv/lib/python3.9/site-packages/edgedb/asyncio_pool.py:775: DeprecationWarning: The "release()" method is deprecated and is scheduled to be removed. Use the query methods on Pool instead.
    await self.pool.release(con)
```

The reason for these warning is that `AsyncIOPool` itself uses deprecated methods like `acquire` and `release`. 

Although I can these warnings only in pytest output and I can suppress them I still want to ask is this expected behaviour or not?

**Comment by elprans** [comment]
The deprecation is intentional.  Use the pool object directly to run queries instead.  For example, instead of:

```
awync with pool.acquire() as con:
    result = await con.query(...)
```

do 

```
result = await pool.query(...)
```

If you need a "block" where the read/write consistency in consequent statements is needed, use a transaction:

```
async with pool.transaction() as tx:
    result = await tx.query(...)
```

**Comment by 1st1** [comment]
@elprans 
> The deprecation is intentional. 

I think the issue is different here:

> The reason for these warning is that AsyncIOPool itself uses deprecated methods like acquire and release.

@fmoor Frederick, can you take a look into this? I think this is similar to https://github.com/edgedb/edgedb-js/pull/137

**Comment by unmade** [comment]
Hey guys!

Thank you so much for resolving the issue so fast! 

I do however want you to know that while the warnings from `AsyncIOPool` are now gone, there are still some warnings left in `transaction.py` module:

```
.venv/lib/python3.9/site-packages/edgedb/transaction.py:137: DeprecationWarning: The "acquire()" method is deprecated and is scheduled to be removed. Use the query methods on Pool instead.
    self._connection = await self._owner.acquire()
```

```
.venv/lib/python3.9/site-packages/edgedb/transaction.py:181: DeprecationWarning: The "release()" method is deprecated and is scheduled to be removed. Use the query methods on Pool instead.
    await self._owner.release(self._connection)
```

cc @fmoor
