### ISSUE TITLE
Make `edgedb.Tuple` compatible with `tuple`

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb-python#296]
Per https://discord.com/channels/841451783728529451/849374935209607199/943568048504328242

**Comment by fmoor** [comment]
It looks like we are missing at least the following:

```
t.__add__(other: edgedb.Tuple) -> edgedb.Tuple
t.__mul__(other: int) -> edgedb.Tuple
t.__rmul__(other: int) -> edgedb.Tuple
t.__getitem__(key: slice) -> any
t.index(value: any, start: int = 0, stop: int = 9223372036854775807, /) -> int
t.count(value: any, /) -> int
```

I'm not sure if these are a good idea or not... Maybe not since it isn't clear what the return type should be.
```
t.__add__(other: tuple) -> ?
t.__radd__(other: tuple) -> ?
```

**Comment by fantix** [comment]
Since 1.0 we started to use the built-in `tuple` type in Python.
