### ISSUE TITLE
Manual rollback transaction

### ISSUE THREAD

**Issue by Pentusha** [edgedb/edgedb-python#312]
I'm looking for method to do a manual rollback on transactions for unit-tests fixture.
I want the database to have no entities left after the tests are finished, and to run each test in a clean database.
I didn't find any an easy and documented way to do this.
Something like:
```python
@pytest.fixture
def client():
    client = create_client()
    for tx in client.transaction():
        with tx:
            yield tx
            tx.rollback()
```

**Comment by elprans** [comment]
The correct way to rollback a transaction is to raise an exception:

```python
class Rollback(Exception):
    pass

@pytest.fixture
def client():
    client = create_client()
    try:
        for tx in client.transaction():
            with tx:
                yield tx
                raise Rollback
    except Rollback:
        pass
```

**Comment by Pentusha** [comment]
Oh, thank you for so quick answer. I think this should be documented.

**Comment by elprans** [comment]
> I think this should be documented.

Absolutely.
