### ISSUE TITLE
Bindings get confused if a linkprop and a regular prop have the same name

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb-python#377]
If you do something like this (on the `cards` test db)
```
v = db.query('''
    select User { deck: {@count, count := 10} }
''')
```
then `v[0].deck[0].count` will produce
```
'edgedb.Object' object has no attribute 'count'
```

**Comment by fantix** [comment]
#379 didn't fix this - because the key in RecordDesc is overwritten by another. The right fix would be to prefix the key of link properties in RecordDesc directly. I'll create a PR soon.
