### ISSUE TITLE
Arrays of enum values cannot be used in parameters

### ISSUE THREAD

**Issue by stealth-toucan** [edgedb/edgedb-python#408]
This works:

```python
client.query("select <schema::Cardinality>$param;", param="One")
```

This does not work:

```python
client.query("select <array<schema::Cardinality>>$param;", param=["One"])
```

This behavior is inconsistent. The issue can be worked around using a double cast, but the DX is not ideal.

- EdgeDB version: `2.9`
- `edgedb-python` version: `1.2.0`

**Comment by ccsv** [comment]
I ran into this problem too. My solution (for now) was use a string instead.
