### ISSUE TITLE
edgedb-python does not run on mac m1

### ISSUE THREAD

**Issue by arogozhnikov** [edgedb/edgedb-python#414]
**Describe the bug**

Following first steps, can't run codegen

**Reproduction**

1. init project
2. add `get-number.edgeql`
3. `pip install edgedb`

error
```console
$ python -m edgedb.codegen
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/axelr/pll/venv/lib/python3.10/site-packages/edgedb/__init__.py", line 24, in <module>
    from edgedb.datatypes.datatypes import (
ImportError: dlopen(/Users/axelr/pll/venv/lib/python3.10/site-packages/edgedb/datatypes/datatypes.cpython-310-darwin.so, 0x0002): tried: '/Users/axelr/pll/venv/lib/python3.10/site-packages/edgedb/datatypes/datatypes.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/axelr/pll/venv/lib/python3.10/site-packages/edgedb/datatypes/datatypes.cpython-310-darwin.so' (no such file), '/Users/axelr/pll/venv/lib/python3.10/site-packages/edgedb/datatypes/datatypes.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

```

**Expected behavior**

A clear and concise description of what you expected to happen. If applicable, add screenshots to help explain your problem.

**Versions (please complete the following information):**

- OS: macos 13.1
- EdgeDB version: {'2.9+4fbadd2'}
- EdgeDB CLI version: EdgeDB CLI 2.2.6+7eabbf9
- `edgedb-python` version: 1.12
- Python version: Python 3.10.9

**Comment by arogozhnikov** [comment]
update: edgedb-python==1.11 works ok 🤷

**Comment by elprans** [comment]
Could be a cibuildwheel bug?

**Comment by AndreasPB** [comment]
Works fine for me (version 1.3.0 on Macbook Air M1)

**Comment by fantix** [comment]
@arogozhnikov This seems to be an issue of the toolchain on your Mac, since we don't have wheels for arm64 yet. A wild search + guess give me [this](https://stackoverflow.com/a/73953565/3316267), but I'm not sure it'll work for you because I cannot reproduce the issue.

Though, I'll look into building arm64 wheels in the next release.
