### ISSUE TITLE
Doesn't work on python3.8

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb-python#47]
Error is:
```
  File "edgedb/protocol/protocol.pyx", line 1, in init edgedb.protocol.protocol
  File "edgedb/pgproto/./uuid.pyx", line 162, in init edgedb.pgproto.pgproto
TypeError: multiple bases have instance lay-out conflict
```

Edgedb-python version is 0.6.1 (latest on pypi at the moment)

**Comment by 1st1** [comment]
You should use the locally installed edgedb-python as outlined in https://edgedb.com/docs/internals/dev. The error you see is fixed in the master branch of `edgedb-python`.

**Comment by 1st1** [comment]
EdgeDB alpha 1 is also quite different from what we have in the master branch; I'd suggest you to develop against the master branch only.
