### ISSUE TITLE
Confusing KeyError on resulting row

### ISSUE THREAD

**Issue by tailhook** [edgedb/edgedb-python#50]
On code like this:
```python
x = edb.fetchone("SELECT ...")
x["id"]
```
I get error like this:
```
KeyError: 'id'
```
But I think it should be something like this:
```
TypeError: 'User' object is not subscriptable
```
Because basically I should write `x.id` instead (and it works).

Or is there any legitimate case when both attribute and item access work on the same row?

(lib version `edgedb==0.7.0a2.dev0+e147670`)

**Comment by 1st1** [comment]
Ah, this isn't a bug. We use `[]` to access link objects. E.g. for

```
SELECT
   User { friend: {name, @weight }}
```

using square brackets on the returned object would allow you to access the `weight` link property:

* `User.friend.name` to access a regular property
* `User['friend']` to access the "friend" link directly; `User['friend'].weight` to access the link property.

So strictly speaking this isn't a bug.

**Comment by elprans** [comment]
Still, the exception message could be improved

**Comment by nsidnev** [comment]
I'd like to take this. But I'm not sure about the errors to raise. Since the brackets are used to access the link objects, it seems to me that the `KeyError` should stay there. So I thought about changing current behaviour to something like this:
```python3
user = conn.fetchone("SELECT User { name, friend: { name } } LIMIT 1")
user['name']  # TypeError: property 'name' should be accessed via dot notation
user['error_key']  # KeyError: link 'error_key' does not exist
```

What do you think about it?

**Comment by 1st1** [comment]
> What do you think about it?

I like it! Please go ahead and submit a PR.
