### ISSUE TITLE
Possibly undefined exception class InternalClientError

### ISSUE THREAD

**Issue by RobertoPrevato** [edgedb/edgedb-python#98]
`asyncio_pool` refers to `errors.InternalClientError` in two conditions, but there is no custom exception `InternalClientError` defined in `errors` namespace.

Should `errors.InternalClientError` be replaced with `ClientError` or one of its subclasses?
The name also rings a bell, because what does it mean for a client error to be "internal"?

Noticed while working on [JS pool](https://github.com/edgedb/edgedb-js/pull/52).

**Comment by 1st1** [comment]
Yeah, please submit a PR.

**Comment by RobertoPrevato** [comment]
Reminder for myself:
* onRelease callback seems to be not tested, add a test to the suite
